'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VisioPriem_v1._0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider=OraOLEDB.Oracle.1;User ID=ReportA21;Password=ReportA21;Data Source=WMOS_PROD;Persist Security Info=False
        '''.
        '''</summary>
        Friend ReadOnly Property db_path() As String
            Get
                Return ResourceManager.GetString("db_path", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogoLittle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogoLittle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT to_char(ah.create_date_time, &apos;YYYY-MM-DD&apos;) AS create_date,
        '''       a.name                                     AS departament_name,
        '''       ah.shpmt_nbr                               AS shpmt_nbr,
        '''       CASE
        '''         WHEN ah.asn_shpmt_type = &apos;L&apos;   THEN &apos;LOCAL&apos;
        '''         ELSE SUBSTR(im.sku_desc, 0, 3)
        '''           END                                    AS brand,
        '''       nvl(ah.ref_field_1, &apos; &apos;)                    AS ref_field_1,
        '''       CASE
        '''         WHEN ah.stat_code = 10 THEN &apos;В транзите&apos;
        '''        [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sql_ASN() As String
            Get
                Return ResourceManager.GetString("sql_ASN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to     SELECT to_char(TRUNC(ch.mod_date_time), &apos;YYYY-MM-DD&apos;)    AS &quot;Дата создания&quot;,
        '''           a.name                                            AS &quot;name&quot;,
        '''           COUNT(ch.plt_id)                                  AS &quot;Allocated&quot;,
        '''           COUNT(ptt.plt_id)                                 AS &quot;Размещены&quot;
        '''      FROM case_hdr ch
        ''' LEFT JOIN prod_trkg_tran ptt ON ch.case_nbr = ptt.cntr_nbr AND ptt.tran_type = &apos;300&apos;
        '''      JOIN wcd_master wm ON ch.cd_master_id = wm.cd_master_id
        '''      JOIN address a ON wm.p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sql_LOTKI() As String
            Get
                Return ResourceManager.GetString("sql_LOTKI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to        SELECT lh.lvl                                                                             AS lane,
        '''              COUNT(DISTINCT lh.posn)                                                            AS all_cell_count,
        '''              COUNT(DISTINCT CASE WHEN caseh.case_nbr    IS NOT NULL THEN lh.posn ELSE NULL END) AS lpn_cell_count,
        '''              COUNT(DISTINCT CASE WHEN carton.carton_nbr IS NOT NULL THEN lh.posn ELSE NULL END) AS okt_cell_count
        '''         FROM locn_hdr lh
        '''    LEFT JOIN Case_Hdr caseh [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sql_SORTER() As String
            Get
                Return ResourceManager.GetString("sql_SORTER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WITH carton_type_location AS
        '''(
        '''SELECT &apos;APL&apos; AS carton_type, &apos;APL&apos; AS item_location FROM dual UNION ALL
        '''SELECT &apos;IVE&apos;,                &apos;ПС&apos;                   FROM dual UNION ALL
        '''SELECT &apos;IVS&apos;,                &apos;ПС&apos;                   FROM dual UNION ALL
        '''SELECT &apos;MAZ&apos;,                &apos;МЕЗОНИН&apos;              FROM dual UNION ALL
        '''SELECT &apos;MHE&apos;,                &apos;МЕЗОНИН&apos;              FROM dual UNION ALL
        '''SELECT &apos;ORB&apos;,                &apos;МЕЗОНИН&apos;              FROM dual UNION ALL
        '''SELECT &apos;OTH&apos;,                &apos;МЕЗОНИН&apos;    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property sql_ZAPAS() As String
            Get
                Return ResourceManager.GetString("sql_ZAPAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
